discord:
    TOKEN: DISCORD_BOT_TOKEN

databases:
    default: sqlite
    sqlite:
      driver: sqlite
      database: Momento\database\discord.db
      log_queries: True
      prefix:
    mysql:
      driver: mysql
      host: 
      database: 
      port:
      user: 
      password: 
      log_queries:
    postgres:
      driver: postgres
      host: 
      database:
      port:
      user:
      password:
      log_queries:
  
config:
  utils:
    bot_logging: True
    bot_settings: True
    bot_utils: True
